#spring:
#  datasource:
#    url: jdbc:mysql:sql7.freesqldatabase.com:3306/sql7295188?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#    username: sql7295188
#    password: y4vQBFADRj
#  jpa:
#    hibernate:
#      ddl-auto: update
#  profiles:
#    active: noauth
